### PR TITLE
EddyVerbruggen/SocialSharing-PhoneGap-Plugin#954 - fix ios crash

### PR DESCRIPTION
**Pull request by eodonohoe**
Verified this fix for the iOS crash

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Cool. Did you the `shareViaEmail` afterwards?

**Comment by eodonohoe** [comment]
Yes, multiple times in testing, and we've eliminated the crash from production.  The pluginInitialize call was the main culprit, but I removed it also from the completion handler because it was redundant, and because it was in a block seemed susceptible to the same crash.

**Comment by EddyVerbruggen** [comment]
Awesome, thanks!

**Comment by EddyVerbruggen** [comment]
At your service: 5.4.1 is now on npm.

**Pull request merged**
