### PR TITLE
Run sharing in main thread

### PR DESCRIPTION
**Pull request by TdoubleG**
In Xcode you will see an error that the ActivityController should run in main thread

### CODE REVIEW

**Comment by murcie** [comment]
Same issue.  I think should be merged.

```
[reports] Main Thread Checker: UI API called on a background thread: -[UIViewController setValue:forKey:]
PID: 56663, TID: 4051744, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   ProjectName                         0x000000010494f8c8 __61-[SocialSharing shareInternal:withOptions:isBooleanResponse:]_block_invoke + 2276
```

**Comment by koraysels** [comment]
could this be the cause of the long  initial load time of the share menu?

**Comment by TdoubleG** [comment]
Yes

**Comment by koraysels** [comment]
cool man, ill just use your branch in my app :D

**Comment by santiq** [comment]
Instead of deleting the line, this should be a configuration option

**Comment by EddyVerbruggen** [comment]
Everybody, please promise me nobody is going to open an issue that Cordova is yelling in the console that this method is taking too long and should _not_ run in the main thread.

**Comment by TdoubleG** [comment]
@santiq it doesn’t make sense to set the line as configuration because it’s an error from the iOS System. You can find it also in the documentation from Apple

**Comment by nice2seeu** [comment]
Wrapping with  dispatch_async(dispatch_get_main_queue(), ^{…});  gets back the quick initial load in my setting.

Before:
```
        if (subject != (id)[NSNull null] && subject != nil) {
          [activityVC setValue:subject forKey:@"subject"];
        }
```
After 
```
    dispatch_async(dispatch_get_main_queue(), ^{ 
        if (subject != (id)[NSNull null] && subject != nil) {
          [activityVC setValue:subject forKey:@"subject"];
        }
    });
```

**Pull request merged**
