### PR TITLE
Use Facebook URL instead of File when present

### PR DESCRIPTION
**Pull request by centogram**

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Thanks! Note that this will functionally change behavior of the plugin. In a patch release. Is that really what we should do?

**Comment by centogram** [comment]
I believe we should because without this the image file itself is the click destination for Facebook rather than the URL.  This at least keeps the sharing feature of the plugin working.

**Comment by EddyVerbruggen** [comment]
If anything, this sounds like a better default anyway. Thanks again!

**Comment by centogram** [comment]
would you be ok releasing the 5.6.5 milestone.  I'd like to incorporate this official package into our next release with this merge.

**Comment by EddyVerbruggen** [comment]
Done!

**Pull request merged**
