### PR TITLE
enhancement for ios

### PR DESCRIPTION
**Pull request by mikealo**
avoid thread blocking on ios

### CODE REVIEW

**Comment by mikealo** [comment]
sorry this is a mess 4b1c68b is the right one

**Comment by EddyVerbruggen** [comment]
Thanks, excellent work!

**Comment by EddyVerbruggen** [comment]
You're now a committer to this repo, but please use the PR mechanism for any changes so we can easily  control when and what is going into master. :+1:

**Comment by mikealo** [comment]
sure, no problem:D

**Pull request merged**
