### PR TITLE
Update README.md error on window.plugins

### PR DESCRIPTION
**Pull request by rgllm**
Now window.plugins is window['plugins']

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
What happended to `window`? Can you perhaps point me at some announcement?

**Comment by rgllm** [comment]
I did not find any documentation about it. I was implementing your plugin and I was getting the error. Various users pointed that solution for the problem.

**Comment by EddyVerbruggen** [comment]
OK fair enough. If anyone has more info please feel free to share here.

**Comment by rgllm** [comment]
Maybe the best solution is adding the two solutions.

**Comment by EddyVerbruggen** [comment]
I just created a new Cordova CLI (8.0.0) app. After waiting for `deviceready` as usual I was able to do `window.plugins.socialsharing.share()`.

**Pull request closed without merging**
