### PR TITLE
configurable excludedActivities

### PR DESCRIPTION
**Pull request by revolunet**
Hey

i added a way to configure the excluded activities from the plist, hope you like it.

Thanks for the great plugin

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
This looks great, thanks a lot! :+1:

**Comment by leylandjacob** [comment]
Is there an example of how this should look in config.xml? The plist version doesn't work and does not look to be the proper syntax anymore. Any help would be much appreciated. 

Thanks

**Comment by revolunet** [comment]
I currently use an after_prepare hook script to update it among other things :

i dont know how to do this via config.xml but would be interested about the solution too :)

```js
var projectName = 'HelloWorld';
var fs = require('fs'),
    plist = require('plist-native'),
    plistPath = 'platforms/ios/' + projectName + '/' + projectName + '-Info.plist',
    plistConf = plist.parse(fs.readFileSync(plistPath));

plistConf.SocialSharingExcludeActivities = [
    'com.apple.UIKit.activity.AssignToContact',
    'com.apple.UIKit.activity.CopyToPasteboard',
    'com.apple.UIKit.activity.Print',
    'com.apple.UIKit.activity.PostToWeibo',
    'com.apple.UIKit.activity.SaveToCameraRoll',
    'com.apple.UIKit.activity.AddToReadingList',
    'com.apple.UIKit.activity.PostToFlickr',
    'com.apple.UIKit.activity.PostToVimeo',
    'com.apple.UIKit.activity.TencentWeibo',
    'com.apple.UIKit.activity.AirDrop'
];


fs.writeFile(plistPath, plist.buildString(plistConf), function(err) {
    if (err) {
        throw err;
    }
});
```

**Comment by leonardiwagner** [comment]
do you guys know if it's possible to exclude activities on Android widget too?

If so, I could work on this ..even not knowing Android very well, but as no one mentioned about excluding activities on Android it seems to not be possible, please confirm.

**Comment by EddyVerbruggen** [comment]
@leonardiwagner confirmed :ballot_box_with_check:

Give it a shot :)

**Comment by isabelleaubron** [comment]
Hi,
since last comments is there a way to exclude activites on Android? and Windows Phone? Thanks

**Pull request merged**
