### PR TITLE
Fix conflicting provider on android

### PR DESCRIPTION
**Pull request by onlydave**
android:authorities need to be unique across all apps installed on your android device.

Installing a second app with this plugin will fail as they'll both try and use the `com.socialsharing.provider` provider.

Using the package name + sharing.provider means this should be unique to app and plugin

### CODE REVIEW

**Comment by onlydave** [comment]
#750

**Comment by onlydave** [comment]
#749

**Comment by onlydave** [comment]
#744, #745, #740

**Comment by onlydave** [comment]
Not sure what `android:authorities` should be.

Options could be:

* `$PACKAGE_NAMEsharing.provider`
* `$PACKAGE_NAMEsocialsharing.provider`
* `$PACKAGE_NAME.socialsharing.provider`
* `$PACKAGE_NAME.sharing.provider`
* `$PACKAGE_NAME.socialsharingphonegap.provider`

Just using `$PACKAGE_NAME.provider` might still conflict with other plugins that have the same idea. 

I've tested all of the above on a nexus 5x and will be pushing a nightly to our QA team today with `$PACKAGE_NAME.socialsharing.provider` in it for testing.

 #740, #744, #745, #749, #750

**Comment by EddyVerbruggen** [comment]
Your code looks good to me - do you want me to wait a bit before merging?

**Comment by onlydave** [comment]
@EddyVerbruggen merge away

**Comment by EddyVerbruggen** [comment]
Sweet! I'll tag a release shortly.

**Comment by EddyVerbruggen** [comment]
@onlydave  can you take a look at why #753 isn't an issue in your case? Do you have other plugins installed using the support library perhaps?

**Comment by onlydave** [comment]
@EddyVerbruggen I think it's probably because i have Android Support Repository installed from the android SDK Manager

**Comment by EddyVerbruggen** [comment]
@onlydave Could also be because you have fi the Camera plugin installed as well.

Anyway, I've now added a framework reference to the v4 support library so folk using PhoneGap Build can use the plugin again.

**Comment by onlydave** [comment]
@EddyVerbruggen no camera plugin but could be a different one. Thanks

**Pull request merged**
